#ifndef WINDOWSINPUT_GLOBAL_H
#define WINDOWSINPUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WINDOWSINPUT_LIBRARY)
#  define WINDOWSINPUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WINDOWSINPUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WINDOWSINPUT_GLOBAL_H
